# site settings
title: CBU Meetings
#theme: minima
email: bioinformatics@childrensnational.org
github_username: BI-CTSICN
rss: false

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
#avatar: "/img/avatar-icon.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: " https://bi-ctsicn.github.io/CBU_Agenda/" # eg. "deanattali.com/beautiful-jekyll"

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

paginate: 5
